# Site settings
title: 경희대학교 SoftCon
email: khusoftcon@gmail.com
description: > # Kyunghee University Conference.
baseurl: /
url: http://khusoftcon.github.io

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->

safe:        false
host:        0.0.0.0
port:        4000
lsi:         false
