# Site settings
title: 경희대학교 SoftCon
email: khusoftcon@gmail.com
description: > # Kyunghee University Conference.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://khusoftcon.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->
